### ISSUE TITLE
Iridium ore and ingots

### ISSUE THREAD

**Issue by Late-Night** [HurtsAsHell/Metallurgic-Industrialization#10]
**Describe the solution you'd like**
check the title

**Describe alternatives you've considered**
cheating in the ore from thermal foundation

**Why would you like this to be implemented?**
because thermal foundation didn't set it to spawn naturally in the world and you have a platinum ore(another ore that TF doesn't have naturally spawn)

**Comment by HurtsAsHell** [comment]
I know that the ore of iridium are not generated but what is the problem? iridium is useless.
However, platinum is generated mainly from metallurgy.

**Comment by Late-Night** [comment]
> 
> 
> I know that the ore of iridium are not generated but what is the problem? iridium is useless.
> However, platinum is generated mainly from metallurgy.

problem is i have zero clue how to make their Iridium generate, and there's no guides online that are up-to-date on how

**Comment by HurtsAsHell** [comment]
But you can get iridium from the pulverizer a second chance
but what do you need iridium for?

**Comment by Late-Night** [comment]
no, that's platinum you get
and i need it for some alloys in TF

**Comment by HurtsAsHell** [comment]
I'm playing the same pack and get iridium

**Comment by Late-Night** [comment]
i'm playing a custom pack
how do i enable the spawning of thermal foundation's iridium

**Comment by HurtsAsHell** [comment]
idk
